config/routes.rb
Rails.application.routes.draw do
  root to: 'contacts#index', as: :contacts

  resources :contacts, only: %i[destroy] do
    collection do
      patch '', action: 'bulk_create', as: 'bulk_create'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true, email: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end

  def bulk_create
    result = ContactsCSVImporter.new.perform(permitted_params.fetch(:contacts_csv_file, nil))

    feedback_message = result ? 'Contacts imported!' : 'Failure to import contacts.'

    redirect_to contacts_path, notice: feedback_message
  end

  def destroy
    find_contact.destroy

    respond_to :json
  end

  private

  def permitted_params
    params.permit(:contacts_csv_file)
  end

  def find_contact
    Contact.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def render_contacts_for_react(contacts)
    json = ActiveModel::Serializer::CollectionSerializer.new(contacts).as_json

    react_component('ContactsController', { initial_items: json }, camelize_props: true)
  end
end

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_with url: bulk_create_contacts_path, method: :patch do |f| %>
  <%= f.file_field :contacts_csv_file %>
  <%= f.submit "Upload" %>
<% end %>

<h1>Contacts</h1>

<%= render_contacts_for_react(@contacts) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactuallyLite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag    'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>